[project]
name = "grubi-sheets"
version = "0.1.0"
description = ""
authors = [
    { name = "Arthur Valadares Campideli", email = "arthur.c.valadares@gmail.com" }
]
readme = "README.md"
requires-python = "<4.0,>=3.12"
dependencies = [
    "click (>=8.3.3,<9.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "tqdm (>=4.67.3,<5.0.0)",
    "future (>=1.0.0,<2.0.0)",
    "odfpy (>=1.4.1,<2.0.0)",
]

[project.scripts]
simulate = "simulator.cli:main"

[tool.poetry]
packages = [{ include = "simulator", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
